version: '3'

services:
  invest-app:
    image: 'ptash/tinkoff-invest-robot:latest'
    container_name: invest-app
    depends_on:
      - invest-db
    ports:
      - 10000:10000
    volumes:
      - ./data/container/logs:/logs
    env_file: env.sandbox
  invest-db:
    image: 'postgres:14.1-alpine'
    container_name: invest-db
    volumes:
      - ./data/container/postgresql:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=posgres
      - POSTGRES_PASSWORD=posgres